[package]
name = "paddling-tongji-thesis"
version = "0.1.1"
entrypoint = "paddling-tongji-thesis/elements.typ"
authors = ["TJ-CSCCG <https://github.com/TJ-CSCCG>"]
license = "MIT"
description = "同济大学本科生毕业设计论文模板 | Tongji University Undergraduate Thesis Template"
repository = "https://github.com/TJ-CSCCG/tongji-undergrad-thesis-typst.git"
keywords = ["Tongji University", "thesis", "undergraduate"]
categories = ["thesis"]
exclude = []

[template]
path = "init-files"
entrypoint = "main.typ"
thumbnail = "thumbnail.webp"
