name: Prepare Release

on:
  push:
    branches:
      - main

jobs:
  apply-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Apply patch and create new branch
        run: |
          chmod +x .github/bin/package_release.sh
          .github/bin/package_release.sh
